version: '3'

services:
  backend:
    build: ./backend_service
    container_name: backend_service
    working_dir: /app
    volumes:
      - ./backend_service:/app
    expose:
      - "5000"
    networks:
      - envoy-net

  envoy:
    image: envoyproxy/envoy:v1.25-latest
    container_name: envoy_proxy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./dlp_filter.lua:/etc/envoy/lua/dlp_filter.lua
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - envoy-net

networks:
  envoy-net:
    driver: bridge